import type { RowData } from "./components/Table";

export const table1Data: RowData[] = [
    {
        firstName: "William",
        lastName: "Nylander",
        team: "TOR",
        goals: 18,
        gamesPlayed: 40,
        bet1: 200,
        bet2: 220,
        bet3: 185,
        bet4: 175
    }, {
        firstName: "JJ",
        lastName: "Peterka",
        team: "UTA",
        goals: 20,
        gamesPlayed: 57,
        bet1: 285,
        bet2: 300,
        bet3: 215,
        bet4: 0
    }, {
        firstName: "Nicolas",
        lastName: "Roy",
        team: "TOR",
        goals: 5,
        gamesPlayed: 54,
        bet1: 900,
        bet2: 800,
        bet3: 510,
        bet4: 600
    }, {
        firstName: "Ryan",
        lastName: "Nugent-Hopkins",
        team: "EDM",
        goals: 13,
        gamesPlayed: 49,
        bet1: 275,
        bet2: 250,
        bet3: 225,
        bet4: 240
    }, {
        firstName: "Owen",
        lastName: "Tippett",
        team: "PHI",
        goals: 19,
        gamesPlayed: 56,
        bet1: 290,
        bet2: 290,
        bet3: 280,
        bet4: 225
    }, {
        firstName: "Mark",
        lastName: "Scheifele",
        team: "WPG",
        goals: 27,
        gamesPlayed: 56,
        bet1: 175,
        bet2: 170,
        bet3: 140,
        bet4: 155
    }, {
        firstName: "Vladislav",
        lastName: "Namestnikov",
        team: "WPG",
        goals: 7,
        gamesPlayed: 55,
        bet1: 450,
        bet2: 440,
        bet3: 410,
        bet4: 475
    }, {
        firstName: "Auston",
        lastName: "Matthews",
        team: "TOR",
        goals: 26,
        gamesPlayed: 51,
        bet1: 175,
        bet2: 170,
        bet3: 148,
        bet4: 145
    }, {
        firstName: "Chris",
        lastName: "Kreider",
        team: "ANA",
        goals: 19,
        gamesPlayed: 50,
        bet1: 245,
        bet2: 220,
        bet3: 215,
        bet4: 240
    }, {
        firstName: "Tomas",
        lastName: "Hertl",
        team: "VGK",
        goals: 22,
        gamesPlayed: 57,
        bet1: 225,
        bet2: 230,
        bet3: 235,
        bet4: 0
    }, {
        firstName: "Alex",
        lastName: "Ovechkin",
        team: "WSH",
        goals: 22,
        gamesPlayed: 59,
        bet1: 145,
        bet2: 140,
        bet3: 148,
        bet4: 160
    }, {
        firstName: "Connor",
        lastName: "McDavid",
        team: "EDM",
        goals: 34,
        gamesPlayed: 58,
        bet1: 105,
        bet2: 105,
        bet3: 100,
        bet4: -105
    }, {
        firstName: "Jake",
        lastName: "DeBrusk",
        team: "VAN",
        goals: 13,
        gamesPlayed: 56,
        bet1: 240,
        bet2: 240,
        bet3: 200,
        bet4: 225
    }, {
        firstName: "Elias",
        lastName: "Pettersson",
        team: "VAN",
        goals: 13,
        gamesPlayed: 49,
        bet1: 240,
        bet2: 240,
        bet3: 200,
        bet4: 275
    }, {
        firstName: "Nikita",
        lastName: "Kucherov",
        team: "TBL",
        goals: 29,
        gamesPlayed: 51,
        bet1: 115,
        bet2: 120,
        bet3: 115,
        bet4: -105
    }
];

export const table2Data: RowData[] = [
    {
        firstName: "Drew",
        lastName: "Doughty",
        team: "LAK",
        goals: 3,
        gamesPlayed: 48,
        bet1: 800,
        bet2: 700,
        bet3: 650,
        bet4: 750
    }, {
        firstName: "Max",
        lastName: "Domi",
        team: "TOR",
        goals: 9,
        gamesPlayed: 55,
        bet1: 425,
        bet2: 480,
        bet3: 360,
        bet4: 300
    }, {
        firstName: "Morgan",
        lastName: "Barron",
        team: "WPG",
        goals: 7,
        gamesPlayed: 47,
        bet1: 750,
        bet2: 800,
        bet3: 410,
        bet4: 525
    }, {
        firstName: "Evan",
        lastName: "Bouchard",
        team: "EDM",
        goals: 15,
        gamesPlayed: 58,
        bet1: 390,
        bet2: 390,
        bet3: 350,
        bet4: 300
    }, {
        firstName: "Devon",
        lastName: "Toews",
        team: "COL",
        goals: 1,
        gamesPlayed: 42,
        bet1: 1100,
        bet2: 1200,
        bet3: 850,
        bet4: 0
    }, {
        firstName: "John",
        lastName: "Tavares",
        team: "TOR",
        goals: 20,
        gamesPlayed: 57,
        bet1: 265,
        bet2: 260,
        bet3: 235,
        bet4: 225
    }, {
        firstName: "Alex",
        lastName: "Killorn",
        team: "ANA",
        goals: 7,
        gamesPlayed: 56,
        bet1: 340,
        bet2: 290,
        bet3: 290,
        bet4: 300
    }, {
        firstName: "Jake",
        lastName: "Walman",
        team: "EDM",
        goals: 5,
        gamesPlayed: 29,
        bet1: 1200,
        bet2: 1100,
        bet3: 575,
        bet4: 750
    }, {
        firstName: "Mitch",
        lastName: "Marner",
        team: "VGK",
        goals: 16,
        gamesPlayed: 57,
        bet1: 280,
        bet2: 270,
        bet3: 0,
        bet4: 0
    }, {
        firstName: "Filip",
        lastName: "Hronek",
        team: "VAN",
        goals: 5,
        gamesPlayed: 57,
        bet1: 750,
        bet2: 650,
        bet3: 700,
        bet4: 700
    }, {
        firstName: "Owen",
        lastName: "Power",
        team: "BUF",
        goals: 4,
        gamesPlayed: 56,
        bet1: 1000,
        bet2: 1100,
        bet3: 750,
        bet4: 750
    }, {
        firstName: "Adam",
        lastName: "Lowry",
        team: "WPG",
        goals: 4,
        gamesPlayed: 44,
        bet1: 500,
        bet2: 550,
        bet3: 450,
        bet4: 550
    }, {
        firstName: "Ryan",
        lastName: "McLeod",
        team: "BUF",
        goals: 11,
        gamesPlayed: 57,
        bet1: 425,
        bet2: 430,
        bet3: 370,
        bet4: 350
    }, {
        firstName: "Matthew",
        lastName: "Knies",
        team: "TOR",
        goals: 14,
        gamesPlayed: 54,
        bet1: 360,
        bet2: 350,
        bet3: 255,
        bet4: 300
    }, {
        firstName: "Teddy",
        lastName: "Blueger",
        team: "VAN",
        goals: 5,
        gamesPlayed: 10,
        bet1: 550,
        bet2: 575,
        bet3: 500,
        bet4: 475
    }
];

export const table3Data: RowData[] = [
    {
        firstName: "Beck",
        lastName: "Malenstyn",
        team: "BUF",
        goals: 4,
        gamesPlayed: 56,
        bet1: 1000,
        bet2: 1100,
        bet3: 650,
        bet4: 900
    }, {
        firstName: "Dylan",
        lastName: "Samberg",
        team: "WPG",
        goals: 0,
        gamesPlayed: 40,
        bet1: 1200,
        bet2: 1300,
        bet3: 1200,
        bet4: 1000
    }, {
        firstName: "Darnell",
        lastName: "Nurse",
        team: "EDM",
        goals: 7,
        gamesPlayed: 58,
        bet1: 1200,
        bet2: 1100,
        bet3: 650,
        bet4: 700
    }, {
        firstName: "Brandon",
        lastName: "Carlo",
        team: "TOR",
        goals: 0,
        gamesPlayed: 34,
        bet1: 2200,
        bet2: 2200,
        bet3: 1500,
        bet4: 1400
    }, {
        firstName: "Drew",
        lastName: "O'Connor",
        team: "VAN",
        goals: 13,
        gamesPlayed: 57,
        bet1: 370,
        bet2: 370,
        bet3: 450,
        bet4: 450
    }, {
        firstName: "Jack",
        lastName: "Drury",
        team: "COL",
        goals: 8,
        gamesPlayed: 55,
        bet1: 550,
        bet2: 550,
        bet3: 460,
        bet4: 0
    }, {
        firstName: "Ryker",
        lastName: "Evans",
        team: "SEA",
        goals: 5,
        gamesPlayed: 41,
        bet1: 1900,
        bet2: 1600,
        bet3: 1200,
        bet4: 1500
    }, {
        firstName: "Brandt",
        lastName: "Clarke",
        team: "LAK",
        goals: 6,
        gamesPlayed: 56,
        bet1: 750,
        bet2: 750,
        bet3: 575,
        bet4: 575
    }, {
        firstName: "Jake",
        lastName: "McCabe",
        team: "TOR",
        goals: 3,
        gamesPlayed: 55,
        bet1: 1000,
        bet2: 1400,
        bet3: 1500,
        bet4: 1200
    }, {
        firstName: "Ty",
        lastName: "Emberson",
        team: "EDM",
        goals: 1,
        gamesPlayed: 53,
        bet1: 2200,
        bet2: 2100,
        bet3: 1500,
        bet4: 1750
    }, {
        firstName: "Jack",
        lastName: "Quinn",
        team: "BUF",
        goals: 12,
        gamesPlayed: 57,
        bet1: 360,
        bet2: 400,
        bet3: 340,
        bet4: 260
    }, {
        firstName: "Tyler",
        lastName: "Myers",
        team: "VAN",
        goals: 1,
        gamesPlayed: 57,
        bet1: 1500,
        bet2: 1300,
        bet3: 1100,
        bet4: 1000
    }, {
        firstName: "Simon",
        lastName: "Benoit",
        team: "TOR",
        goals: 0,
        gamesPlayed: 49,
        bet1: 0,
        bet2: 0,
        bet3: 1900,
        bet4: 2000
    }, {
        firstName: "Cole",
        lastName: "Koepke",
        team: "WPG",
        goals: 5,
        gamesPlayed: 40,
        bet1: 850,
        bet2: 900,
        bet3: 500,
        bet4: 600
    }, {
        firstName: "Sam",
        lastName: "Steel",
        team: "DAL",
        goals: 7,
        gamesPlayed: 57,
        bet1: 500,
        bet2: 470,
        bet3: 380,
        bet4: 475
    }
];
